kind: Deployment
apiVersion: apps/v1
metadata:
    name: lets-talk
    labels:
        app: lets-talk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lets-talk
  template:
    metadata:
      labels:
        app: lets-talk
    spec:
      containers:
      - name: lets-talk
        image: peterchau/lets-talk:latest
        ports:
          - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REACT_APP_STREAM
          value: "http://lets-talk.ngrok.io/test.mjpg"
        - name: REACT_APP_API
          value: "http://localhost:8080"
